### ISSUE TITLE
제가 멀 해야 하면 되나요 ?

### ISSUE THREAD

**Issue by moka-a** [appkr/project-ryan#1]
프로젝트 기본 생성은 다 하신것 같은데 .. 

멀 하면 될까요 ??

**Comment by appkr** [comment]
@moka-a 😉 

목요일 때까지는 제가 짬짬이
- 화면 설계: 레이아웃 (심미적인 부분은 신경쓰지 않기로 했지요)
- 스토리보드: x버튼을 누르면 y가 동작한다.
- 개발계획: 업무분장 및 일정
까지만 준비해 볼게요. [0612 회의록 액션아이템](https://github.com/appkr/team-ryan/blob/master/0612/meeting_minutes.md#액션-아이템)에 3번입니다.

1번은 호영님이 링크는 공유했고, 재룡님 IDE 플로그인 소개하기로 했고, 
2번 migration, seed data, URL endpoint(Routing) 만들어야, 일을 시작할 수 있는데.. 목요일 회의 뒤로 미룰게요.

**Comment by moka-a** [comment]
넵! 감사합니다!
