### ISSUE TITLE
랜딩 페이지 만들기

### ISSUE THREAD

**Issue by moka-a** [appkr/project-ryan#11]
- 팔로잉한 유저 모두 가져오기
- 유저들의 활동 로그 가져오기

**Comment by yihoyoung** [comment]
제가 할게요.

**Comment by moka-a** [comment]
에고.. 모르고 제가 했네요 ㅠ 혹시 하셨나요 ? @yihoyoung

**Comment by moka-a** [comment]
팔로잉한 유저 모두 가져오는것만 구현 완료
